# Generated by Django 4.2.7 on 2025-12-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("original_url", models.TextField()),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
