# Generated by Django 4.2.7 on 2025-12-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="click",
            index=models.Index(
                fields=["clicked_at"], name="idx_tracking_click_clicked_at"
            ),
        ),
    ]
